#include "MapLoader.h"

//empty constructor
MapLoader::MapLoader() {
}

//destructor
MapLoader::~MapLoader() {
	//call delete on map pointer created
	delete parsedMap;
	parsedMap = NULL;
}

//load parsed map

Map* MapLoader::LoadMap(std::string mapFilePath) {

	Map parsedMap;

	cout << "Verifying map before loading..." << endl; 

	parsedMap = ReadMap(mapFilePath);

	cout << "Map successfully generated, returning parsed map..." << endl;

	return parsedMap;
}

//copy constructor
MapLoader::MapLoader(const MapLoader& map) {

}

//stream insertion operator << cout (override "<<")
//overload assignment operator 
//copy constructor for maploader class




//read map file
Map* MapLoader::ReadMap(std::string mapFilePath) {

	Map parsedMap;

	std::string line{ "" };
	std::ifstream openFile(mapFilePath);

	if (!openFile.is_open()) {
		cout << "Unable to open the file selected. Please choose a valid text file." << endl;
		exit(1);
	}

	if (openFile.peek() == std::ifstream::traits_type::eof()) {
		cout << "The file selected is empty. Please choose a different file." << endl;
		exit(1);
	}

	if (openFile.is_open()) {
		while (getline(openFile, line)) {
			if (line.find("[continents]" == 0)) {

				cout << "Found the continent section..." << endl;
				int continentId = 0;
				while (getline(openFile, line)) {
					if (line.length() != 0) {
						std::string info = line;
						std::vector<string> words = MapLoader::split(line, ' ');

						if (words.size() != NUM_ENTRIES_CONTINENT) {
							cout << "The file has invalid continent information." << endl;
							exit(1);
						}

						int numberOfArmies = std::stoi(words[1]);

						//Adding continent to map object, 0 is the string
						parsedMap.AddContinent(words[0], ++continentId, numberOfArmies);

						cout << "Adding continent number " << continentId << endl;
						cout << "Continent name: " << words[0] << endl;
						cout << "Number of bonus armies: " << numberOfArmies << endl;
					}
				}
			}

			cout << "Finished adding continents." << endl;

			if (line.find("[countries]" == 0)) {
				cout << "Found the countries section..." << endl;
				while (getline(openFile, line)) {
					if (line.length() != 0) {
						std::string info = line;
						std::vector<string> words = MapLoader::split(line, ' ');

						if (words.size() < NUM_ENTRIES_TERRITORIES) {
							cout << "The file has invalid territory information." << endl;
							exit(1);
						}

						int territoryId = std::stoi(words[0]);
						int continentId = std::stoi(words[2]);

						//Adding territory to map object, 
						//0 is the territory id, 
						//1 is the name, 
						//2 is the country it belongs to (must match country id generated by map)
						parsedMap.AddTerritory(words[1], territoryId, continentId);

						cout << "Adding country number " << territoryId << endl;
						cout << "Country name: " << words[1] << endl;
						cout << "Country belongs to continent number " << continentId << endl;
					}
				}
			}

			cout << "Finished adding countries." << endl;

			if (line.find("[borders]" == 0)) {
				cout << "Found the borders section..." << endl;
				while (getline(openFile, line)) {
					if (line.length() != 0) {
						std::string info = line;
						std::vector<string> words = MapLoader::split(line, ' ');

						std::vector<int> borders;
						int countryId = std::stoi(words[0]);

						for (int i = 1; i < words.size() - 1; ++i) {

							borders.push_back(std::stoi(words[i]));
						}

						//Adding borders to map object, 
						parsedMap.AddBorders(countryId, borders);

						cout << "Adding borders to country number " << countryId << endl;
					}
				}
			}
			
		}
	}

	cout << "Finished adding borders." << endl;
	cout << "Parsing map file..." << endl;

	openFile.close;

	return parsedMap;
}

std::vector<string> MapLoader::split(string s, string delim) {

	vector<string> words;

	size_t pos = 0;
	std::string token;

	while ((pos = s.find(delim)) != std::string::npos) {

		token = s.substr(0, pos);
		words.push_back(token);
		s.erase(0, pos + delim.length());
	}

	return words;
}



